### ISSUE TITLE
Unable to programatically stop the stubby server

### ISSUE THREAD

**Issue by surf66** [felixzapata/gulp-stubby-server#4]
Think I have a fix - will fork and submit pull request.

**Comment by felixzapata** [comment]
Hi. Ok. What is the problem exactly?

**Comment by surf66** [comment]
We are running tests in a CI environment and need to shutdown stubby server once tests have completed. At the minute it stays running.

**Comment by felixzapata** [comment]
ah ok.. if you submit the pull request I will review it as soon as possible. 

I used the server to run tests locally but I think that I did not need (in my case) run the server in the CI environment.

**Comment by surf66** [comment]
I'm going to submit it now - i'm unsure on your test setup. Finding it difficult to write tests.

**Comment by surf66** [comment]
or you can have a brief look here before I submit: https://github.com/felixzapata/gulp-stubby-server/compare/master...surf66:master

**Comment by felixzapata** [comment]
Hi, i think that for your case it is better to use _stubby4node_ directly in your CI environment as a task. I mean, I think is not a good idea to do this, with a gulp task.

Example:

```
var Stubby = require('stubby').Stubby;
var fs = require('fs');
var colors = require('colors');
var options = {
    location: 'localhost',
    stubs: 8000,
    mute: false,
    tls: 8443,
    admin: 8001
};

options.data = JSON.parse(fs.readFileSync('test/fixtures/myFakeData.json'));

var mockService = new Stubby();

mockService.start(options, function(err) {
    if (err) {
        console.log('err');
    }
    console.log(colors.cyan('Stubby HTTP server listening on port ' + options.stubs));
    console.log(colors.cyan('Stubby HTTPS server listening on port ' + options.tls));
    console.log(colors.cyan('Admin server listening on port ' + options.admin));
});

// mockService.stop(function() {
//     console.log(colors.green('Stop Stubby HTTP server listening on port ' + options.stubs));
//     console.log(colors.green('Stop Stubby HTTPS server listening on port ' + options.tls));
//     console.log(colors.green('Stop server listening on port ' + options.admin));
// });

```

This way, you can stop the server wherever you want.

**Comment by surf66** [comment]
Ok cool will check it out, thanks.

Here is our code so you can understand what we have done.

```
var gulp    = require('gulp'),
    stubby  = require('gulp-stubby-server'),
    config  = require('../config').stubby,
    stubbyServer;


gulp.task('stubby-start', function(cb) {
    var options = {
        stubs: 8000,
        tls: 8443,
        admin: 8010,
        files: config.src
    };

    stubbyServer = stubby(options, cb);
});

gulp.task('stubby-stop', function(cb) {
    stubbyServer.stop();
});
```

We run these two tasks using `run-sequence`. stubby-start before tests and stubby-stop after tests. Only problem is this plugin does not expose any functionality to stop the stubby server.

**Comment by felixzapata** [comment]
Hi, sorry I was busy. Both solutions are valid. I will try to merge later the pull request.

**Comment by felixzapata** [comment]
hi @surf66, i´ve merged your pull request and released a new version. I have problems now to update the package in the npm registry. As soon I fix this problem, the package will be update with the new version.

**Comment by felixzapata** [comment]
ok, the new version is available via npm

**Comment by surf66** [comment]
Cool, great stuff! Thanks, Tom.
